version: "2"
services:
  combined:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./docs:/workdir/docs"
    environment:
      PORT: 8080
      PROXY: nodejs
      PHANTOMJS: process
